version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5500:5500"

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro